name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  library:
    name: Library
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - name: Select Xcode 26.0
        run: sudo xcode-select -s /Applications/Xcode_26.0.app
      - name: Run tests
        run: make test
      # - name: Build for library evolution
      #   run: make build-for-library-evolution
